# Generated by Django 6.1.1 on 2026-09-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('Business', 'Business'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Engineering', 'Engineering'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
